#!/usr/bin/env python3
"""Call one fixed Wenmai Alpha standard API endpoint."""

from _wenmai_api import run_api


if __name__ == "__main__":
    run_api(
        script_name='alpha_youtube_scraper.py',
        path='/alpha/youtube-scraper',
        required_fields=[],
        sample_params={'is3D': False, 'is4K': False, 'isHD': False, 'hasCC': False, 'is360': False, 'isHDR': False, 'isLive': False, 'isVR180': False, 'isBought': False, 'videoType': 'video', 'dateFilter': 'month', 'maxResults': 3, 'hasLocation': False, 'hasSubtitles': False, 'lengthFilter': 'between420', 'sortVideosBy': 'NEWEST', 'sortingOrder': 'relevance', 'saveSubsToKVS': False, 'searchQueries': ['Crawlee'], 'oldestPostDate': '2024-01-01', 'subtitlesFormat': 'srt', 'maxResultStreams': 0, 'maxResultsShorts': 0, 'downloadSubtitles': False, 'subtitlesLanguage': 'en', 'preferAutoGeneratedSubtitles': False},
    )
